name: Sync Upstream

on:
  schedule:
    - cron: '0 0 1,15 * *' # 每月1号和15号的0点触发
  workflow_dispatch: # 允许手动触发此工作流

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'TalentSmallPanda'
          git config --global user.email '1334762516@qq.com'

      - name: Add upstream
        run: git remote add upstream https://github.com/adazzle/react-data-grid.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push to sync-upstream branch
        run: |
          git checkout -b sync-upstream
          git push origin sync-upstream -f

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge upstream changes'
          branch: 'sync-upstream'
          title: 'Sync upstream'
          body: 'This PR syncs the upstream changes.'
